// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rianfowler/fist-bump-chat/ent/runtime.go

const (
	Version = "v0.12.4"                                         // Version of ent codegen.
	Sum     = "h1:LddPnAyxls/O7DTXZvUGDj0NZIdGSu317+aoNLJWbD8=" // Sum of ent codegen.
)
